<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseLaboratory>true</UseLaboratory>
        <RootNamespace>ColonyManagerRedux.Managers</RootNamespace>
        <AssemblyName>ColonyManagerRedux.Managers</AssemblyName>
        <!-- TODO: Remove and fix -->
        <NoWarn>CA1502;CA1506</NoWarn>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\ColonyManagerRedux\ColonyManagerRedux.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Publicize Include="Assembly-CSharp:RimWorld.Pawn_TrainingTracker.learned" />
        <Publicize Include="Assembly-CSharp:RimWorld.PawnTable.def" />
        <Publicize Include="Assembly-CSharp:RimWorld.Pawn_TrainingTracker.SetWanted" />
        <Publicize Include="Assembly-CSharp:RimWorld.CompMilkable.Active" />
        <Publicize Include="Assembly-CSharp:RimWorld.CompShearable.Active" />
        <Publicize Include="Assembly-CSharp:RimWorld.CompHasGatherableBodyResource.GatherResourcesIntervalDays" />
        <Publicize Include="Assembly-CSharp:RimWorld.CompDeepDrill.GetNextResource" />
        <Publicize Include="Assembly-CSharp:RimWorld.CompFlickable.wantSwitchOn" />
        <Publicize Include="Assembly-CSharp:Verse.GenFilePaths.FolderUnderSaveData" />
        <Publicize Include="Assembly-CSharp:Verse.Widgets.InfoCardButtonWorker" />
    </ItemGroup>
</Project>
