<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseLaboratory>true</UseLaboratory>
        <RootNamespace>ColonyManagerRedux.AnimalGenetics</RootNamespace>
        <AssemblyName>ColonyManagerRedux.AnimalGenetics</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\ColonyManagerRedux\ColonyManagerRedux.csproj">
            <CopyLocal>False</CopyLocal>
            <Private>false</Private>
        </ProjectReference>
        <ProjectReference Include="..\ColonyManagerRedux.Managers\ColonyManagerRedux.Managers.csproj">
            <CopyLocal>False</CopyLocal>
            <Private>false</Private>
        </ProjectReference>
        <Reference Include="AnimalGenetics">
            <HintPath>$(RimWorldSteamWorkshopFolderPath)\2830943477\$(RimWorldVersion)\Assemblies\AnimalGenetics.dll</HintPath>
            <CopyLocal>False</CopyLocal>
            <Private>false</Private>
        </Reference>
    </ItemGroup>
</Project>
